# Engenharia de Features e Pré-processamento Blindado contra Vazamento de Dados

Este notebook corresponde à **Etapa 5** do nosso Roteiro de Desenvolvimento do **Tech Challenge (Fase 1)**.

### 🎯 Objetivo desta Etapa:
Evitar que informações do holdout influenciem estatísticas aprendidas no treino. Primeiro separamos treino e teste; depois ajustamos winsorização IQR, imputação, escala e codificação somente com o treino. O holdout recebe apenas `transform`, usando os parâmetros já aprendidos.

Utilizaremos pipelines modulares do Scikit-Learn:
1. **`IQRWinsorizer`**: aprende os limites de clipping somente nos dados de treino.
2. **`ColumnTransformer`**: aplica transformações numéricas e categóricas apropriadas.
3. **`StandardScaler`, `OneHotEncoder` e `SimpleImputer`**: ajustados no treino e reutilizados sem novo ajuste no holdout.

In [15]:
import os
import sys
from pathlib import Path
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

# Configuração de logs simples
import logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

## 📂 1. Carregando a Base Bruta e Derivando a Target

O treino parte dos dados brutos. A winsorização e as outras transformações aprendem seus parâmetros somente depois da separação entre treino e holdout.

In [16]:
# Ajuste do caminho relativo para rodar a partir do repositório local
BASE_DIR = Path(os.getcwd()).resolve()
if BASE_DIR.name == 'notebooks':
    BASE_DIR = BASE_DIR.parent
sys.path.insert(0, str(BASE_DIR))

from src.dataset import binarize_target, load_raw_data, validate_data
from src.features import (
    split_features_target,
    get_feature_lists,
    IQRWinsorizer,
    build_preprocessing_pipeline,
)

RAW_DATA_PATH = BASE_DIR / "data" / "raw" / "desafio_nps_fase_1.csv"

df = load_raw_data(RAW_DATA_PATH)
validate_data(df)
df = binarize_target(df)
print(f"Base bruta carregada! Linhas: {df.shape[0]} | Colunas: {df.shape[1]}")
df.head()

2026-10-15 21:10:38,809 - INFO - Carregando dados originais de: /home/userdev/dev/projetos/POSTECH_AI_SCIENTIST/TECH_CHALLENGE_ECOMMERCE/data/raw/desafio_nps_fase_1.csv
2026-10-15 21:10:38,818 - INFO - Dados carregados com sucesso! Linhas: 2500, Colunas: 19
2026-10-15 21:10:38,819 - INFO - Iniciando validação de consistência e integridade dos dados...
2026-10-15 21:10:38,826 - INFO - Validação de integridade concluída com sucesso! Todos os testes de qualidade passaram.
2026-10-15 21:10:38,828 - INFO - Aplicando engenharia de target (binarização do NPS)...
2026-10-15 21:10:38,831 - INFO - Binarização concluída. Proporção de Detratores (classe positiva):84.36%

Base bruta carregada! Linhas: 2500 | Colunas: 20

,customer_id,customer_age,customer_region,customer_tenure_months,order_id,order_value,items_quantity,discount_value,payment_installments,delivery_time_days,delivery_delay_days,freight_value,delivery_attempts,customer_service_contacts,resolution_time_days,nps_score,repeat_purchase_30d,complaints_count,csat_internal_score,is_detractor
0,1,63,Nordeste,14,50001,139.73,4,39.35,4,2,2,55.53,3,0,4,6.9,0,3,6.5,1
1,2,20,Sul,1,50002,458.95,2,9.51,10,6,4,28.23,3,0,10,2.4,0,3,0.0,1
2,3,46,Nordeste,111,50003,507.06,5,42.82,6,6,1,40.99,1,4,5,4.8,0,7,1.5,1
3,4,52,Centro-Oeste,117,50004,302.19,2,19.58,9,5,2,35.24,3,1,11,5.9,0,4,0.3,1
4,5,56,Norte,50,50005,253.06,1,29.37,11,13,1,39.32,1,1,0,6.1,0,3,7.9,1

## 🔒 2. Divisão Estratificada de Features e Target

Separamos features e target e então criamos o holdout. Nenhum cálculo de limites IQR, imputação, escala ou categorias usa o holdout para ajustar parâmetros.

In [17]:
# Exclusões e target são centralizadas em src.features
X, y = split_features_target(df)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    stratify=y,
    random_state=42,
)

print("=== DIVISÃO TREINO / HOLDOUT ===")
print(f"X treino: {X_train.shape} | detratores: {y_train.mean() * 100:.2f}%")
print(f"X holdout: {X_test.shape} | detratores: {y_test.mean() * 100:.2f}%")

2026-10-15 21:10:38,868 - INFO - Divisão X/y concluída. Shape de X: (2500, 14), Shape de y: (2500,)

=== DIVISÃO TREINO / HOLDOUT ===
X treino: (2000, 14) | detratores: 84.35%
X holdout: (500, 14) | detratores: 84.40%

## 🛠️ 3. Separação de Tipos de Colunas com Base no Treino

As colunas numéricas e categóricas são identificadas a partir de `X_train`; o holdout não participa da definição do pré-processamento.

In [18]:
num_features, cat_features = get_feature_lists(X_train)

print(f"-> Features Numéricas ({len(num_features)}):\n{num_features}\n")
print(f"-> Features Categóricas ({len(cat_features)}):\n{cat_features}")

2026-10-15 21:10:38,913 - INFO - Features Numéricas identificadas (13): ['customer_age', 'customer_tenure_months', 'order_value', 'items_quantity', 'discount_value', 'payment_installments', 'delivery_time_days', 'delivery_delay_days', 'freight_value', 'delivery_attempts', 'customer_service_contacts', 'resolution_time_days', 'complaints_count']
2026-10-15 21:10:38,914 - INFO - Features Categóricas identificadas (1): ['customer_region']

-> Features Numéricas (13):
['customer_age', 'customer_tenure_months', 'order_value', 'items_quantity', 'discount_value', 'payment_installments', 'delivery_time_days', 'delivery_delay_days', 'freight_value', 'delivery_attempts', 'customer_service_contacts', 'resolution_time_days', 'complaints_count']

-> Features Categóricas (1):
['customer_region']

## ⚙️ 4. Pipeline de Winsorização e Pré-processamento

O winsorizador, imputadores, scaler e encoder fazem parte do mesmo fluxo. No `fit`, eles aprendem somente com `X_train`; depois usamos `transform` no holdout sem recalcular estatísticas.

In [19]:
# 1. Winsorizar somente as variáveis definidas para tratamento de outliers.
winsorized_columns = [
    column
    for column in (
        "customer_service_contacts",
        "delivery_delay_days",
        "complaints_count",
    )
    if column in num_features
]
winsorizer = IQRWinsorizer(columns=winsorized_columns)

# 2. Pré-processamento numérico/categórico centralizado na implementação do projeto.
preprocessor = build_preprocessing_pipeline(num_features, cat_features)

# 3. Pipeline unificada. O fit do winsorizador e do preprocessor verá apenas X_train.
preprocessing_pipeline = Pipeline(
    steps=[
        ("winsorizer", winsorizer),
        ("preprocessor", preprocessor),
    ]
)

print("✓ Pipeline completa de pré-processamento instanciada com sucesso!")

2026-10-15 21:10:38,931 - INFO - Construindo pipeline de pré-processamento (ColumnTransformer)...

✓ Pipeline completa de pré-processamento instanciada com sucesso!

## 🧪 5. Ajustando no Treino e Transformando o Holdout

Ajustamos a pipeline exclusivamente em `X_train`. O holdout passa por `transform`, recebendo os limites IQR, imputações, médias/desvios e categorias aprendidos no treino.

In [20]:
X_train_trans = preprocessing_pipeline.fit_transform(X_train, y_train)
X_test_trans = preprocessing_pipeline.transform(X_test)

print("=== COMPARAÇÃO DE DIMENSÕES ===")
print(f"Shape original de X_train: {X_train.shape}")
print(f"Shape após transformação do treino: {X_train_trans.shape}")
print(f"Shape original de X_test: {X_test.shape}")
print(f"Shape após transformação do holdout: {X_test_trans.shape}")
print(f"Proporção de detratores no holdout: {y_test.mean() * 100:.2f}%")

encoded_cats = (
    preprocessing_pipeline.named_steps["preprocessor"]
    .named_transformers_["cat"]
    .named_steps["onehot"]
    .get_feature_names_out(cat_features)
)
all_feature_names = num_features + list(encoded_cats)

print(f"\n✓ Total de colunas geradas na pipeline: {len(all_feature_names)}")
print("Nomes das colunas pós-transformação:")
for index, column_name in enumerate(all_feature_names):
    print(f" - [{index}]: {column_name}")

=== COMPARAÇÃO DE DIMENSÕES ===
Shape original de X_train: (2000, 14)
Shape após transformação do treino: (2000, 18)
Shape original de X_test: (500, 14)
Shape após transformação do holdout: (500, 18)
Proporção de detratores no holdout: 84.40%

✓ Total de colunas geradas na pipeline: 18
Nomes das colunas pós-transformação:
 - [0]: customer_age
 - [1]: customer_tenure_months
 - [2]: order_value
 - [3]: items_quantity
 - [4]: discount_value
 - [5]: payment_installments
 - [6]: delivery_time_days
 - [7]: delivery_delay_days
 - [8]: freight_value
 - [9]: delivery_attempts
 - [10]: customer_service_contacts
 - [11]: resolution_time_days
 - [12]: complaints_count
 - [13]: customer_region_Centro-Oeste
 - [14]: customer_region_Nordeste
 - [15]: customer_region_Norte
 - [16]: customer_region_Sudeste
 - [17]: customer_region_Sul

## 📝 6. Inspecionando a Matriz Transformada do Treino

Inspecionamos o conjunto de treino já transformado. As estatísticas e limites mostrados foram aprendidos apenas a partir do treino; não foram ajustados usando o holdout.

In [21]:
df_train_trans = pd.DataFrame(X_train_trans, columns=all_feature_names)
print("Estatísticas resumidas do treino transformado:")
display(df_train_trans.describe().round(3).head(3))

print("\nPrimeiros 3 registros transformados do treino:")
df_train_trans.head(3)

Estatísticas resumidas do treino transformado:

,customer_age,customer_tenure_months,order_value,items_quantity,discount_value,payment_installments,delivery_time_days,delivery_delay_days,freight_value,delivery_attempts,customer_service_contacts,resolution_time_days,complaints_count,customer_region_Centro-Oeste,customer_region_Nordeste,customer_region_Norte,customer_region_Sudeste,customer_region_Sul
count,2000.0,2000.0,2000.0,2000.0,2000.0,2000.0,2000.0,2000.0,2000.0,2000.0,2000.0,2000.0,2000.0,2000.000,2000.000,2000.000,2000.000,2000.000
mean,-0.0,0.0,-0.0,-0.0,0.0,-0.0,0.0,-0.0,-0.0,0.0,0.0,0.0,-0.0,0.187,0.190,0.202,0.206,0.214
std,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.390,0.393,0.401,0.405,0.411

Primeiros 3 registros transformados do treino:

,customer_age,customer_tenure_months,order_value,items_quantity,discount_value,payment_installments,delivery_time_days,delivery_delay_days,freight_value,delivery_attempts,customer_service_contacts,resolution_time_days,complaints_count,customer_region_Centro-Oeste,customer_region_Nordeste,customer_region_Norte,customer_region_Sudeste,customer_region_Sul
0,-0.175171,-0.551689,-1.325795,1.498951,0.244958,-1.267080,1.339497,-0.126104,0.793705,-0.009752,0.493231,-1.581709,1.070569,1.0,0.0,0.0,0.0,0.0
1,-0.040424,0.234774,-0.232895,0.907415,-0.751877,0.636872,1.605957,-0.820890,0.207721,-1.228779,1.861418,1.589782,1.070569,0.0,0.0,0.0,1.0,0.0
2,-0.983652,1.137749,-1.102054,0.315880,0.735724,0.636872,-0.525727,-1.515677,-0.134171,1.209274,0.493231,-1.581709,0.496845,0.0,0.0,0.0,1.0,0.0